stages:
  - pre-commit
  - review
  - test
  - deploy

before_script:
  - apt-get update
  - apt-get install redis-server -y
  - redis-server --daemonize yes
  - python -V
  - pip install tox

pre-commit:
  stage: review
  image: python:3.6-buster
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  script:
    - pip install pre-commit
    - pre-commit run --all-files

.test-py36:
  needs: []
  stage: test
  image: python:3.6-buster

.test-py37:
  needs: []
  stage: test
  image: python:3.7-buster

.test-py38:
  needs: []
  stage: test
  image: python:3.8-buster

.test-py39:
  needs: []
  stage: test
  image: python:3.9-buster

test-36-django31:
  extends: .test-py36
  script:
    - tox -e py36-django31
    - bash <(curl -s https://codecov.io/bash)

test-37-django31:
  extends: .test-py37
  script:
    - tox -e py37-django31
    - bash <(curl -s https://codecov.io/bash)

test-38-django31:
  extends: .test-py38
  script:
    - tox -e py38-django31
    - bash <(curl -s https://codecov.io/bash)

test-39-django31:
  extends: .test-py39
  script:
    - tox -e py39-django31
    - bash <(curl -s https://codecov.io/bash)

deploy-pypi:
  stage: deploy
  image: python:3.7-buster

  before_script:
    - pip install twine

  script:
    - python setup.py sdist
    - twine upload dist/*

  only:
    - tags


danger:
  needs: []
  stage: review
  before_script:
    - gem install danger-gitlab
  script:
    - danger --fail-on-errors=true

include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
