# Generated by Django 3.1.2 on 2021-01-17 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0017_remove_fleetup_permission"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("inactivity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inactivitypingconfig",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Groups subject to the inactivity ping. If empty, applies to all groups.",
                related_name="_inactivitypingconfig_groups_+",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="inactivitypingconfig",
            name="states",
            field=models.ManyToManyField(
                blank=True,
                help_text="States subject to the inactivity ping. If empty, applies to all states.",
                related_name="_inactivitypingconfig_states_+",
                to="authentication.State",
            ),
        ),
        migrations.CreateModel(
            name="LeaveOfAbsence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start",
                    models.DateField(help_text="The start of the leave of absence."),
                ),
                (
                    "end",
                    models.DateField(
                        blank=True,
                        help_text="The end of the leave of absence. Leave blank for an indefinite leave.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
